name: 'helm'

env:
  FOO: "BAR"

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  helm:
    name: 'Helm dashboards with https url'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: https dashboards
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm pull grafana/grafana --version 10.1.4 --untar
        ls -lha
        cd grafana
        helm template my-grafana --dry-run --debug ./ -f ../dashboards.yaml
        # our case:
        # helm upgrade my-grafana grafana/grafana --version 10.1.4 -f dashboards.yaml

    - name: path dashboards
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm pull grafana/grafana --version 10.1.4 --untar
        ls -lha
        #cp dashboards/* grafana/dashboards
        cd grafana
        ls -lha
        helm template my-grafana --dry-run --debug ./ -f ../dashboards.yaml

